# Generated by Django 5.1 on 2024-08-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=254)),
                ("autor", models.CharField(max_length=100)),
                ("no_paginas", models.IntegerField()),
                ("fecha_publicacion", models.DateField(help_text="Fecha Publicacion")),
                (
                    "clasificacion",
                    models.IntegerField(
                        choices=[
                            (0, ""),
                            (1, "Romance"),
                            (2, "Aventura"),
                            (3, "Ficción"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
    ]
