# Generated by Django 5.1 on 2024-09-16 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        help_text="Nombre del usuario que realiza la reserva",
                        max_length=100,
                    ),
                ),
                (
                    "fecha_reserva",
                    models.DateField(help_text="Fecha en que se realiza la reserva"),
                ),
                (
                    "fecha_devolucion",
                    models.DateField(help_text="Fecha en que debe devolverse el libro"),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        help_text="Libro reservado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.libro",
                    ),
                ),
            ],
        ),
    ]
