# Generated by Django 5.1 on 2024-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0002_reserva"),
    ]

    operations = [
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("nombre_completo", models.CharField(max_length=254)),
                ("clave", models.CharField(max_length=254)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("A", "Administrador"),
                            ("B", "Bibliotecario"),
                            ("E", "Estudiante"),
                        ],
                        default="E",
                        max_length=254,
                    ),
                ),
            ],
        ),
    ]
