# Generated by Django 5.1 on 2024-10-19 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0003_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_reserva", models.DateField(auto_now_add=True)),
                (
                    "fecha_devolucion",
                    models.DateField(help_text="Fecha en que debe devolverse el libro"),
                ),
                (
                    "estado",
                    models.IntegerField(
                        choices=[
                            (1, "Prestado"),
                            (2, "Reservado"),
                            (3, "Devuelto"),
                            (4, "con novedad"),
                        ],
                        default=1,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "libro",
                    models.ForeignKey(
                        help_text="Libro reservado",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="biblioteca.libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="biblioteca.usuario",
                    ),
                ),
            ],
        ),
    ]
