# Generated by Django 5.1 on 2024-11-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0004_prestamo"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="foto",
            field=models.ImageField(
                default="libros/default.pmg", upload_to="img/libros"
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (1, "Prestado"),
                    (2, "Renovado"),
                    (3, "Devuelto"),
                    (4, "con novedad"),
                ],
                default=1,
            ),
        ),
    ]
