# Generated by Django 5.1 on 2024-11-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0005_libro_foto_alter_prestamo_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="foto",
            field=models.ImageField(
                blank=True,
                default="libros/default.png",
                null=True,
                upload_to="biblioteca/static/img/libros",
            ),
        ),
    ]
