# Generated by Django 5.1 on 2024-10-05 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0002_contract_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="contract",
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("agua", "Agua"),
                            ("electricidad", "Electricidad"),
                            ("gas", "Gas"),
                            ("telefono", "Telefonía"),
                        ],
                        max_length=50,
                    ),
                ),
                ("numero_contrato", models.CharField(max_length=50, unique=True)),
                ("fecha_inicio", models.DateField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_emision", models.DateField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("pagada", "Pagada"), ("pendiente", "Pendiente")],
                        default="pendiente",
                        max_length=50,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas",
                        to="gestion_usuarios.contrato",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Contract",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
