# Generated by Django 5.1 on 2024-11-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Desarrollador",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("correo_electronico", models.EmailField(max_length=254, unique=True)),
                ("contrasena", models.CharField(max_length=255)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Líder de Proyecto", "Líder de Proyecto"),
                            ("Desarrollador", "Desarrollador"),
                        ],
                        default="Desarrollador",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "miembros",
                    models.ManyToManyField(
                        related_name="equipos", to="project.desarrollador"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_limite", models.DateField()),
                ("prioridad", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=50)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.desarrollador",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.equipo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiderProyecto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.equipo",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="desarrollador",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="project.usuario"
            ),
        ),
    ]
