# Generated by Django 5.1 on 2024-11-16 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="descripcion",
            field=models.TextField(default="Sin descripción"),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="miembros",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
