# Generated by Django 5.1 on 2024-11-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(default="Nombre predeterminado", max_length=100),
        ),
    ]
